### PR TITLE
empties errors for re-used stateDB

### LINKED ISSUE #821: The test TestDatabase_BulkLoadProducesBlocks in the Carmen package is flaky
A flaky test in the `carmen` package caused a [stress test](https://jenkins.fantom.network/job/Carmen/job/Stress-Tests/40/console) on Jenkins to fail.

To reproduce the issue, run
```
$ go test ./carmen -count 10 --timeout 1000000s
```

The error produced looks like this:
```
--- FAIL: TestDatabase_BulkLoadProducesBlocks (0.23s)
    database_test.go:412: unexpected error during query evaluation: failed to compute hash: injectedErr
        failed to compute hash: injectedErr
        failed to compute hash: injectedErr
        failed to compute hash: injectedErr
--- FAIL: TestDatabase_CloseDB_Unfinished_Queries (0.18s)
    database_test.go:810: cannot close query: failed to compute hash: injectedErr
--- FAIL: TestDatabase_AddBlock_QueryBlock_Parallel (0.91s)
    database_test.go:1008: cannot query block: failed to compute hash: injectedErr
signal: killed
FAIL	github.com/Fantom-foundation/Carmen/go/carmen	168.419s
FAIL
```

### PR DESCRIPTION
**Pull request by kjezek**
This PR fixes #821 

The key part is that it clears the list of errors of re-used `stateDB`. Before this fix, errors accumulated in one test propagated to other tests as the `stateDB` instances are re-used from a pool.

Furthermore, a few places were extended with closing the database in tests (it did not relate to the fixed bug).

### CODE REVIEW

**Review by HerbertJordan — APPROVED** [review]
Great find, thanks for fixing that!

As I understand, only the change in `go/state/state_db.go` is the actual fix. I would suggest to put this into its own PR and do the cleanups in the tests in an independent PR. If we would encounter problems in the future, this makes it easier to understand the changes in these PRs.

**Comment by kjezek** [comment]
ok, I put all other changes to #832 as they are related to that PR

**Review by HerbertJordan — DISMISSED** [review]

File: go/state/state_db.go [hunk 1]
```diff
@@ -1330,6 +1330,7 @@ func (s *stateDB) resetState(state State) {
 	s.ResetBlockContext()
 	s.storedDataCache.Clear()
 	s.reincarnation = map[common.Address]uint64{}
+	s.errors = s.errors[0:0]
```
[the remark this answers is not in the document]
Comment (kjezek) [reply go/state/state_db.go:1333]: ok, I added a test. I found out that there is no test that verifies the re-used `stateDB` is reset, so I tested it fully

**Review by HerbertJordan — APPROVED** [review]

File: go/state/state_db_test.go [hunk 2]
```diff
@@ -3269,6 +3269,94 @@ func TestStateDB_StateDBCanNotEndABlockIfCommitIsNotAllowed(t *testing.T) {
...
+	checkEmpty(db, false)
+
+	if err := db.Check(); !errors.Is(err, injectedErr) {
+		t.Errorf("db should fail")
+	}
+
+	db.EndTransaction()
+
+	// re-cycle the same state
+	db.(*nonCommittableStateDB).resetState(state)
```
Comment (petr-hanzl) [inline go/state/state_db_test.go:3352]: How about we create a private factory func that returns a pointer to the object `nonCommittableStateDB` instead of the interface `NonCommittableStateDB` and use it here to avoid casting? Assuming we call the private factory inside the public one.

File: go/state/state_db_test.go [hunk 3]
```diff
@@ -3269,6 +3269,94 @@ func TestStateDB_StateDBCanNotEndABlockIfCommitIsNotAllowed(t *testing.T) {
...
+	db.SetCode(address1, make([]byte, 10))
+	db.SetNonce(address1, 0x2)
+	db.CreateAccount(common.Address{0xC}) // triggers injected error
+	db.AddAddressToAccessList(common.Address{0xD})
+
+	checkEmpty(db, false)
+
+	if err := db.Check(); !errors.Is(err, injectedErr) {
+		t.Errorf("db should fail")
+	}
```
Comment (petr-hanzl) [inline go/state/state_db_test.go:3347]: I think you should check the error and the error type in a separate condition.

**Review by petr-hanzl — APPROVED** [review]

File: go/state/state_db_test.go (hunk 2 above)
Comment (HerbertJordan) [reply go/state/state_db_test.go]: Fixed
